//
// Created by Sebastian on 8/14/2020.
//

#ifndef BASIC_00_EXAMPLE_PACIENTEASINTOMATICO_H
#define BASIC_00_EXAMPLE_PACIENTEASINTOMATICO_H


class PacienteAsintomatico {

};


#endif //BASIC_00_EXAMPLE_PACIENTEASINTOMATICO_H
